#!/bin/bash
#
# Regenerates src/games.js from the folders under "Image Resources".
#
# The browser cannot list a directory on disk, so the folder list is baked into
# a JS file that index.html loads with a <script> tag. A plain <script> works
# when opening index.html directly from Finder, unlike fetch().
#
# Run this after adding, renaming or removing images:
#
#     bash tools/generate_games.sh
#
# Or just double-click tools/Update Games.command.
#
# Requires only what macOS already ships: /bin/bash and coreutils.
# No Python, Node, npm or any other install.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEB_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)/src"
OUTPUT="$WEB_ROOT/games.js"

IMAGE_EXTENSIONS='jpg|jpeg|png|webp|gif|avif|bmp|svg'

# ---------------------------------------------------------------------------
# Locate "Image Resources". It may sit inside src/ or beside it, so moving the
# folder around does not silently break every image path.
# ---------------------------------------------------------------------------
SOURCE_DIR=""
for candidate in "$WEB_ROOT/Image Resources" "$WEB_ROOT/../Image Resources"; do
    if [ -d "$candidate" ]; then
        SOURCE_DIR="$(cd "$candidate" && pwd)"
        break
    fi
done

if [ -z "$SOURCE_DIR" ]; then
    echo "error: no 'Image Resources' folder found. Looked in:"
    echo "  $WEB_ROOT/Image Resources"
    echo "  $WEB_ROOT/../Image Resources"
    exit 1
fi

# Path from src/ (where index.html and games.js live) to the image folder:
# "Image Resources" when inside src/, "../Image Resources" when beside it.
case "$SOURCE_DIR" in
    "$WEB_ROOT"/*) PREFIX="${SOURCE_DIR#"$WEB_ROOT"/}" ;;
    *)            PREFIX="../${SOURCE_DIR##*/}" ;;
esac

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Percent-encode a path segment. '%' is handled first so the escapes we add
# are not themselves re-encoded. Only spaces occur in the current filenames,
# but the rest are cheap insurance for names added later.
urlencode() {
    printf '%s' "$1" | LC_ALL=C sed \
        -e 's/%/%25/g' \
        -e 's/ /%20/g' \
        -e 's/#/%23/g' \
        -e 's/?/%3F/g' \
        -e 's/&/%26/g' \
        -e 's/+/%2B/g' \
        -e "s/'/%27/g" \
        -e 's/(/%28/g' \
        -e 's/)/%29/g' \
        -e 's/,/%2C/g'
}

# Escape a string for use inside a JSON double-quoted value.
json_escape() {
    printf '%s' "$1" | LC_ALL=C sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

# Alt text: drop every trailing extension ("photo.jpg.webp" -> "photo") and
# collapse runs of whitespace (the two-space "  Strawberry.jpg" -> "Strawberry").
label_from() {
    printf '%s' "$1" \
        | LC_ALL=C sed -E 's/(\.[^.]*)+$//' \
        | tr -s '[:space:]' ' ' \
        | LC_ALL=C sed -e 's/^ *//' -e 's/ *$//'
}

# ---------------------------------------------------------------------------
# Build the manifest
# ---------------------------------------------------------------------------
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
    printf '/* AUTO-GENERATED by tools/generate_games.sh -- do not edit by hand.\n'
    printf ' * Regenerate with:  bash tools/generate_games.sh\n'
    printf ' */\n'
    printf 'window.GAMES = [\n'
} > "$TMP"

deck_count=0
image_total=0

while IFS= read -r folder; do
    [ -n "$folder" ] || continue

    # Images directly inside this folder, case-insensitively sorted.
    files=$(find "$SOURCE_DIR/$folder" -mindepth 1 -maxdepth 1 -type f ! -name '.*' -print \
        | sed "s|^$SOURCE_DIR/$folder/||" \
        | grep -Ei "\.($IMAGE_EXTENSIONS)$" \
        | LC_ALL=C sort -f || true)

    count=0
    img_count=0
    images_block="$TMP.images.$$"
    : > "$images_block"

    if [ -n "$files" ]; then
        while IFS= read -r filename; do
            [ -n "$filename" ] || continue
            src="$(urlencode "$PREFIX/$folder/$filename")"
            label="$(json_escape "$(label_from "$filename")")"
            if [ "$img_count" -gt 0 ]; then printf ',\n' >> "$images_block"; fi
            printf '            {\n                "src": "%s",\n                "label": "%s"\n            }' \
                "$src" "$label" >> "$images_block"
            count=$((count + 1))
            img_count=$((img_count + 1))
        done <<< "$files"
    fi

    if [ "$deck_count" -gt 0 ]; then printf ',\n' >> "$TMP"; fi
    printf '    {\n' >> "$TMP"
    printf '        "id": "%s",\n' "$(json_escape "$folder")" >> "$TMP"
    printf '        "name": "%s",\n' "$(json_escape "$folder")" >> "$TMP"
    printf '        "pairCount": %d,\n' "$((count / 2))" >> "$TMP"
    if [ "$count" -eq 0 ]; then
        printf '        "images": []\n' >> "$TMP"
    else
        printf '        "images": [\n' >> "$TMP"
        cat "$images_block" >> "$TMP"
        printf '\n        ]\n' >> "$TMP"
    fi
    printf '    }' >> "$TMP"

    rm -f "$images_block"
    deck_count=$((deck_count + 1))
    image_total=$((image_total + count))

    if [ "$count" -eq 0 ]; then
        printf '  %-14s no images - will be listed but not playable\n' "$folder:"
    else
        printf '  %-14s %d images, %d pairs\n' "$folder:" "$count" "$((count / 2))"
    fi
done <<< "$(find "$SOURCE_DIR" -mindepth 1 -maxdepth 1 -type d ! -name '.*' -print \
            | sed "s|^$SOURCE_DIR/||" | LC_ALL=C sort -f)"

printf '\n];\n' >> "$TMP"

if [ "$deck_count" -eq 0 ]; then
    echo "error: no subfolders found under $SOURCE_DIR"
    exit 1
fi

cp "$TMP" "$OUTPUT"

echo ""
echo "wrote ${OUTPUT#"$SCRIPT_DIR/.."/}"
echo "read from ${SOURCE_DIR#"$SCRIPT_DIR/.."/}"
echo "$deck_count folders, $image_total images"
echo ""
echo "Reload the game in your browser to pick up the new list."
