/* AUTO-GENERATED by tools/generate_games.sh -- do not edit by hand.
 * Regenerate with:  bash tools/generate_games.sh
 */
window.GAMES = [
    {
        "id": "Animals",
        "name": "Animals",
        "pairCount": 10,
        "images": [
            {
                "src": "Image%20Resources/Animals/Bull.webp",
                "label": "Bull"
            },
            {
                "src": "Image%20Resources/Animals/Bunny.jpg",
                "label": "Bunny"
            },
            {
                "src": "Image%20Resources/Animals/Camel.jpg.webp",
                "label": "Camel"
            },
            {
                "src": "Image%20Resources/Animals/Cow.webp",
                "label": "Cow"
            },
            {
                "src": "Image%20Resources/Animals/Deer.webp",
                "label": "Deer"
            },
            {
                "src": "Image%20Resources/Animals/Dog1.webp",
                "label": "Dog1"
            },
            {
                "src": "Image%20Resources/Animals/Elephant.webp",
                "label": "Elephant"
            },
            {
                "src": "Image%20Resources/Animals/horse.jpg",
                "label": "horse"
            },
            {
                "src": "Image%20Resources/Animals/Jaguar.webp",
                "label": "Jaguar"
            },
            {
                "src": "Image%20Resources/Animals/Moiuntain%20Goa.jpg",
                "label": "Moiuntain Goa"
            },
            {
                "src": "Image%20Resources/Animals/Monkey.webp",
                "label": "Monkey"
            },
            {
                "src": "Image%20Resources/Animals/Owl.webp",
                "label": "Owl"
            },
            {
                "src": "Image%20Resources/Animals/Penguin.webp",
                "label": "Penguin"
            },
            {
                "src": "Image%20Resources/Animals/Polar%20Bear.jpg",
                "label": "Polar Bear"
            },
            {
                "src": "Image%20Resources/Animals/Rabbit.webp",
                "label": "Rabbit"
            },
            {
                "src": "Image%20Resources/Animals/Shjeep.webp",
                "label": "Shjeep"
            },
            {
                "src": "Image%20Resources/Animals/Tiger%20-%201.webp",
                "label": "Tiger - 1"
            },
            {
                "src": "Image%20Resources/Animals/Tiger.jpeg",
                "label": "Tiger"
            },
            {
                "src": "Image%20Resources/Animals/Wolf.jpg",
                "label": "Wolf"
            },
            {
                "src": "Image%20Resources/Animals/Zebra.jpg",
                "label": "Zebra"
            }
        ]
    },
    {
        "id": "Flowers",
        "name": "Flowers",
        "pairCount": 18,
        "images": [
            {
                "src": "Image%20Resources/Flowers/Amaranth.jpg",
                "label": "Amaranth"
            },
            {
                "src": "Image%20Resources/Flowers/Anemone.jpg",
                "label": "Anemone"
            },
            {
                "src": "Image%20Resources/Flowers/Bergamot.jpg",
                "label": "Bergamot"
            },
            {
                "src": "Image%20Resources/Flowers/blossoming-orange-pot-marigold.jpg.webp",
                "label": "blossoming-orange-pot-marigold"
            },
            {
                "src": "Image%20Resources/Flowers/blue-cornflower-flower-head-centaurea-cyan.jpg.webp",
                "label": "blue-cornflower-flower-head-centaurea-cyan"
            },
            {
                "src": "Image%20Resources/Flowers/Chrysanthemum.jpg",
                "label": "Chrysanthemum"
            },
            {
                "src": "Image%20Resources/Flowers/Craspedia.jpg",
                "label": "Craspedia"
            },
            {
                "src": "Image%20Resources/Flowers/dandelion-flower.jpg.webp",
                "label": "dandelion-flower"
            },
            {
                "src": "Image%20Resources/Flowers/dandelion-seed.jpg.webp",
                "label": "dandelion-seed"
            },
            {
                "src": "Image%20Resources/Flowers/Delphinium.jpeg",
                "label": "Delphinium"
            },
            {
                "src": "Image%20Resources/Flowers/frangipani-plumeri.jpg.webp",
                "label": "frangipani-plumeri"
            },
            {
                "src": "Image%20Resources/Flowers/Gladiolus.jpg",
                "label": "Gladiolus"
            },
            {
                "src": "Image%20Resources/Flowers/Hibiscus.jpeg",
                "label": "Hibiscus"
            },
            {
                "src": "Image%20Resources/Flowers/Larkspur.jpg",
                "label": "Larkspur"
            },
            {
                "src": "Image%20Resources/Flowers/Linden.jpg.webp",
                "label": "Linden"
            },
            {
                "src": "Image%20Resources/Flowers/lobelia-cardinalis.jpg.webp",
                "label": "lobelia-cardinalis"
            },
            {
                "src": "Image%20Resources/Flowers/lotus-flower%20-%201.jpg.webp",
                "label": "lotus-flower - 1"
            },
            {
                "src": "Image%20Resources/Flowers/lotus-flower.jpg.webp",
                "label": "lotus-flower"
            },
            {
                "src": "Image%20Resources/Flowers/mauve.jpg.webp",
                "label": "mauve"
            },
            {
                "src": "Image%20Resources/Flowers/Mums.jpg",
                "label": "Mums"
            },
            {
                "src": "Image%20Resources/Flowers/Nigella.jpg",
                "label": "Nigella"
            },
            {
                "src": "Image%20Resources/Flowers/orange.jpg.webp",
                "label": "orange"
            },
            {
                "src": "Image%20Resources/Flowers/Orchid.jpg.webp",
                "label": "Orchid"
            },
            {
                "src": "Image%20Resources/Flowers/Pink%20Cherry%20blossom.jpeg",
                "label": "Pink Cherry blossom"
            },
            {
                "src": "Image%20Resources/Flowers/pink-flower.jpg.webp",
                "label": "pink-flower"
            },
            {
                "src": "Image%20Resources/Flowers/pink-lotus.jpg.webp",
                "label": "pink-lotus"
            },
            {
                "src": "Image%20Resources/Flowers/poppy%20-%201.jpg.webp",
                "label": "poppy - 1"
            },
            {
                "src": "Image%20Resources/Flowers/Poppy.jpeg",
                "label": "Poppy"
            },
            {
                "src": "Image%20Resources/Flowers/Ranunculus.jpg",
                "label": "Ranunculus"
            },
            {
                "src": "Image%20Resources/Flowers/Rose%20-%201.jpeg",
                "label": "Rose - 1"
            },
            {
                "src": "Image%20Resources/Flowers/Rose.jpeg",
                "label": "Rose"
            },
            {
                "src": "Image%20Resources/Flowers/Snapdragon.jpg",
                "label": "Snapdragon"
            },
            {
                "src": "Image%20Resources/Flowers/sun%20flower.jpeg",
                "label": "sun flower"
            },
            {
                "src": "Image%20Resources/Flowers/Zinnia-%201.jpeg",
                "label": "Zinnia- 1"
            },
            {
                "src": "Image%20Resources/Flowers/Zinnia-%202.jpg",
                "label": "Zinnia- 2"
            },
            {
                "src": "Image%20Resources/Flowers/Zinnia.jpeg",
                "label": "Zinnia"
            }
        ]
    },
    {
        "id": "Fruit",
        "name": "Fruit",
        "pairCount": 18,
        "images": [
            {
                "src": "Image%20Resources/Fruit/Apple.jpg",
                "label": "Apple"
            },
            {
                "src": "Image%20Resources/Fruit/Apricot.jpeg",
                "label": "Apricot"
            },
            {
                "src": "Image%20Resources/Fruit/Avacado.jpeg",
                "label": "Avacado"
            },
            {
                "src": "Image%20Resources/Fruit/Banana.jpeg",
                "label": "Banana"
            },
            {
                "src": "Image%20Resources/Fruit/Blackberry.jpeg",
                "label": "Blackberry"
            },
            {
                "src": "Image%20Resources/Fruit/Blueberry.jpeg",
                "label": "Blueberry"
            },
            {
                "src": "Image%20Resources/Fruit/Cantalope.jpg",
                "label": "Cantalope"
            },
            {
                "src": "Image%20Resources/Fruit/Cherry.jpeg",
                "label": "Cherry"
            },
            {
                "src": "Image%20Resources/Fruit/Coconut.jpeg",
                "label": "Coconut"
            },
            {
                "src": "Image%20Resources/Fruit/Dragon%20Fruit.jpeg",
                "label": "Dragon Fruit"
            },
            {
                "src": "Image%20Resources/Fruit/Fig.jpeg",
                "label": "Fig"
            },
            {
                "src": "Image%20Resources/Fruit/Grapes.jpg",
                "label": "Grapes"
            },
            {
                "src": "Image%20Resources/Fruit/Grapes1.jpeg",
                "label": "Grapes1"
            },
            {
                "src": "Image%20Resources/Fruit/Guava.jpeg",
                "label": "Guava"
            },
            {
                "src": "Image%20Resources/Fruit/Honey%20Dew.jpeg",
                "label": "Honey Dew"
            },
            {
                "src": "Image%20Resources/Fruit/Kiwi.jpeg",
                "label": "Kiwi"
            },
            {
                "src": "Image%20Resources/Fruit/Lemon.jpeg",
                "label": "Lemon"
            },
            {
                "src": "Image%20Resources/Fruit/Lime.jpeg",
                "label": "Lime"
            },
            {
                "src": "Image%20Resources/Fruit/Manago%20-%201.jpeg",
                "label": "Manago - 1"
            },
            {
                "src": "Image%20Resources/Fruit/Manago%20-%202.jpeg",
                "label": "Manago - 2"
            },
            {
                "src": "Image%20Resources/Fruit/Manago.jpeg",
                "label": "Manago"
            },
            {
                "src": "Image%20Resources/Fruit/Melon.jpg",
                "label": "Melon"
            },
            {
                "src": "Image%20Resources/Fruit/Orange-1.jpeg",
                "label": "Orange-1"
            },
            {
                "src": "Image%20Resources/Fruit/Orange.jpg",
                "label": "Orange"
            },
            {
                "src": "Image%20Resources/Fruit/Papaya.jpeg",
                "label": "Papaya"
            },
            {
                "src": "Image%20Resources/Fruit/Peach%20-%201.jpeg",
                "label": "Peach - 1"
            },
            {
                "src": "Image%20Resources/Fruit/Peach.jpg",
                "label": "Peach"
            },
            {
                "src": "Image%20Resources/Fruit/Pineapple.jpg",
                "label": "Pineapple"
            },
            {
                "src": "Image%20Resources/Fruit/Piotaya%20Fruit.jpeg",
                "label": "Piotaya Fruit"
            },
            {
                "src": "Image%20Resources/Fruit/Plum.jpeg",
                "label": "Plum"
            },
            {
                "src": "Image%20Resources/Fruit/Pomegranate.jpeg",
                "label": "Pomegranate"
            },
            {
                "src": "Image%20Resources/Fruit/Rassberry%20-%201.jpeg",
                "label": "Rassberry - 1"
            },
            {
                "src": "Image%20Resources/Fruit/Rassberry.jpeg",
                "label": "Rassberry"
            },
            {
                "src": "Image%20Resources/Fruit/Strawberry.jpg",
                "label": "Strawberry"
            },
            {
                "src": "Image%20Resources/Fruit/Water%20Apple.jpeg",
                "label": "Water Apple"
            },
            {
                "src": "Image%20Resources/Fruit/Watermelon.jpg",
                "label": "Watermelon"
            }
        ]
    },
    {
        "id": "Furniture",
        "name": "Furniture",
        "pairCount": 10,
        "images": [
            {
                "src": "Image%20Resources/Furniture/armchair.svg",
                "label": "armchair"
            },
            {
                "src": "Image%20Resources/Furniture/bed.svg",
                "label": "bed"
            },
            {
                "src": "Image%20Resources/Furniture/bookshelf.svg",
                "label": "bookshelf"
            },
            {
                "src": "Image%20Resources/Furniture/coat-rack.svg",
                "label": "coat-rack"
            },
            {
                "src": "Image%20Resources/Furniture/coffee-table.svg",
                "label": "coffee-table"
            },
            {
                "src": "Image%20Resources/Furniture/desk-lamp.svg",
                "label": "desk-lamp"
            },
            {
                "src": "Image%20Resources/Furniture/dining-chair.svg",
                "label": "dining-chair"
            },
            {
                "src": "Image%20Resources/Furniture/dining-table.svg",
                "label": "dining-table"
            },
            {
                "src": "Image%20Resources/Furniture/nightstand.svg",
                "label": "nightstand"
            },
            {
                "src": "Image%20Resources/Furniture/office-chair.svg",
                "label": "office-chair"
            },
            {
                "src": "Image%20Resources/Furniture/ottoman.svg",
                "label": "ottoman"
            },
            {
                "src": "Image%20Resources/Furniture/rocking-chair.svg",
                "label": "rocking-chair"
            },
            {
                "src": "Image%20Resources/Furniture/shoe-rack.svg",
                "label": "shoe-rack"
            },
            {
                "src": "Image%20Resources/Furniture/side-table.svg",
                "label": "side-table"
            },
            {
                "src": "Image%20Resources/Furniture/sideboard.svg",
                "label": "sideboard"
            },
            {
                "src": "Image%20Resources/Furniture/sofa.svg",
                "label": "sofa"
            },
            {
                "src": "Image%20Resources/Furniture/tv-stand.svg",
                "label": "tv-stand"
            },
            {
                "src": "Image%20Resources/Furniture/wall-mirror.svg",
                "label": "wall-mirror"
            },
            {
                "src": "Image%20Resources/Furniture/wardrobe.svg",
                "label": "wardrobe"
            },
            {
                "src": "Image%20Resources/Furniture/writing-desk.svg",
                "label": "writing-desk"
            }
        ]
    },
    {
        "id": "Travel",
        "name": "Travel",
        "pairCount": 16,
        "images": [
            {
                "src": "Image%20Resources/Travel/Argentina.avif",
                "label": "Argentina"
            },
            {
                "src": "Image%20Resources/Travel/Brazil.avif",
                "label": "Brazil"
            },
            {
                "src": "Image%20Resources/Travel/Canada.avif",
                "label": "Canada"
            },
            {
                "src": "Image%20Resources/Travel/Chile.avif",
                "label": "Chile"
            },
            {
                "src": "Image%20Resources/Travel/China.avif",
                "label": "China"
            },
            {
                "src": "Image%20Resources/Travel/Colombia.avif",
                "label": "Colombia"
            },
            {
                "src": "Image%20Resources/Travel/Costa%20Rica.avif",
                "label": "Costa Rica"
            },
            {
                "src": "Image%20Resources/Travel/Croatia.avif",
                "label": "Croatia"
            },
            {
                "src": "Image%20Resources/Travel/Great%20Wall.jpg",
                "label": "Great Wall"
            },
            {
                "src": "Image%20Resources/Travel/Greece.avif",
                "label": "Greece"
            },
            {
                "src": "Image%20Resources/Travel/Iceland.avif",
                "label": "Iceland"
            },
            {
                "src": "Image%20Resources/Travel/India.avif",
                "label": "India"
            },
            {
                "src": "Image%20Resources/Travel/Indonesia.avif",
                "label": "Indonesia"
            },
            {
                "src": "Image%20Resources/Travel/Italy.avif",
                "label": "Italy"
            },
            {
                "src": "Image%20Resources/Travel/Japan.avif",
                "label": "Japan"
            },
            {
                "src": "Image%20Resources/Travel/Kenya.avif",
                "label": "Kenya"
            },
            {
                "src": "Image%20Resources/Travel/London.avif",
                "label": "London"
            },
            {
                "src": "Image%20Resources/Travel/Madagascar.avif",
                "label": "Madagascar"
            },
            {
                "src": "Image%20Resources/Travel/Mexico.avif",
                "label": "Mexico"
            },
            {
                "src": "Image%20Resources/Travel/Morocco.avif",
                "label": "Morocco"
            },
            {
                "src": "Image%20Resources/Travel/Nepal.avif",
                "label": "Nepal"
            },
            {
                "src": "Image%20Resources/Travel/New%20Zeland.avif",
                "label": "New Zeland"
            },
            {
                "src": "Image%20Resources/Travel/Norway.avif",
                "label": "Norway"
            },
            {
                "src": "Image%20Resources/Travel/Peru.avif",
                "label": "Peru"
            },
            {
                "src": "Image%20Resources/Travel/Philippines.avif",
                "label": "Philippines"
            },
            {
                "src": "Image%20Resources/Travel/Portugal.avif",
                "label": "Portugal"
            },
            {
                "src": "Image%20Resources/Travel/Sweden.avif",
                "label": "Sweden"
            },
            {
                "src": "Image%20Resources/Travel/Switzerland.avif",
                "label": "Switzerland"
            },
            {
                "src": "Image%20Resources/Travel/sydney.jpeg",
                "label": "sydney"
            },
            {
                "src": "Image%20Resources/Travel/Thailand.avif",
                "label": "Thailand"
            },
            {
                "src": "Image%20Resources/Travel/Turkey.avif",
                "label": "Turkey"
            },
            {
                "src": "Image%20Resources/Travel/Vietnam.avif",
                "label": "Vietnam"
            }
        ]
    }
];
