/* AUTO-GENERATED by tools/generate_games.sh -- do not edit by hand.
 * Regenerate with:  bash tools/generate_games.sh
 */
window.GAMES = [
    {
        "id": "Animals",
        "name": "Animals",
        "pairCount": 9,
        "images": [
            {
                "src": "Image%20Resources/Animals/Bull.webp",
                "label": "Bull"
            },
            {
                "src": "Image%20Resources/Animals/Bunny.jpg",
                "label": "Bunny"
            },
            {
                "src": "Image%20Resources/Animals/Camel.jpg.webp",
                "label": "Camel"
            },
            {
                "src": "Image%20Resources/Animals/Cow.webp",
                "label": "Cow"
            },
            {
                "src": "Image%20Resources/Animals/Deer.webp",
                "label": "Deer"
            },
            {
                "src": "Image%20Resources/Animals/Dog1.webp",
                "label": "Dog1"
            },
            {
                "src": "Image%20Resources/Animals/Elephant.webp",
                "label": "Elephant"
            },
            {
                "src": "Image%20Resources/Animals/horse.jpg",
                "label": "horse"
            },
            {
                "src": "Image%20Resources/Animals/Jaguar.webp",
                "label": "Jaguar"
            },
            {
                "src": "Image%20Resources/Animals/Moiuntain%20Goa.jpg",
                "label": "Moiuntain Goa"
            },
            {
                "src": "Image%20Resources/Animals/Monkey.webp",
                "label": "Monkey"
            },
            {
                "src": "Image%20Resources/Animals/Owl.webp",
                "label": "Owl"
            },
            {
                "src": "Image%20Resources/Animals/Penguin.webp",
                "label": "Penguin"
            },
            {
                "src": "Image%20Resources/Animals/Polar%20Bear.jpg",
                "label": "Polar Bear"
            },
            {
                "src": "Image%20Resources/Animals/Rabbit.webp",
                "label": "Rabbit"
            },
            {
                "src": "Image%20Resources/Animals/Shjeep.webp",
                "label": "Shjeep"
            },
            {
                "src": "Image%20Resources/Animals/Tiger.webp",
                "label": "Tiger"
            },
            {
                "src": "Image%20Resources/Animals/Wolf.jpg",
                "label": "Wolf"
            },
            {
                "src": "Image%20Resources/Animals/Zebra.jpg",
                "label": "Zebra"
            }
        ]
    },
    {
        "id": "Flowers",
        "name": "Flowers",
        "pairCount": 10,
        "images": [
            {
                "src": "Image%20Resources/Flowers/blossoming-orange-pot-marigold-flower-isolated-16334687.jpg.webp",
                "label": "blossoming-orange-pot-marigold-flower-isolated-16334687"
            },
            {
                "src": "Image%20Resources/Flowers/blue-cornflower-flower-head-centaurea-cyanus-16453007.jpg.webp",
                "label": "blue-cornflower-flower-head-centaurea-cyanus-16453007"
            },
            {
                "src": "Image%20Resources/Flowers/dandelion-flower-dphotography.jpg.webp",
                "label": "dandelion-flower-dphotography"
            },
            {
                "src": "Image%20Resources/Flowers/dandelion-seed-flying-away-2262744.jpg.webp",
                "label": "dandelion-seed-flying-away-2262744"
            },
            {
                "src": "Image%20Resources/Flowers/Delphinium.jpeg",
                "label": "Delphinium"
            },
            {
                "src": "Image%20Resources/Flowers/frangipani-plumeria-flower-5201524.jpg.webp",
                "label": "frangipani-plumeria-flower-5201524"
            },
            {
                "src": "Image%20Resources/Flowers/Hibiscus.jpeg",
                "label": "Hibiscus"
            },
            {
                "src": "Image%20Resources/Flowers/lobelia-cardinalis-431547.jpg.webp",
                "label": "lobelia-cardinalis-431547"
            },
            {
                "src": "Image%20Resources/Flowers/lotus-flower-8341397.jpg.webp",
                "label": "lotus-flower-8341397"
            },
            {
                "src": "Image%20Resources/Flowers/lotus-flower-isolated-white-background-39241417.jpg.webp",
                "label": "lotus-flower-isolated-white-background-39241417"
            },
            {
                "src": "Image%20Resources/Flowers/mauve-flower-composition-1-690383.jpg.webp",
                "label": "mauve-flower-composition-1-690383"
            },
            {
                "src": "Image%20Resources/Flowers/orange-color-hibiscus-flower-green-leaves-isolated-white-background-path-orange-color-hibiscus-flower-green-leaves-123652458.jpg.webp",
                "label": "orange-color-hibiscus-flower-green-leaves-isolated-white-background-path-orange-color-hibiscus-flower-green-leaves-123652458"
            },
            {
                "src": "Image%20Resources/Flowers/Pink%20Cherry%20blossom.jpeg",
                "label": "Pink Cherry blossom"
            },
            {
                "src": "Image%20Resources/Flowers/pink-flower-233395.jpg.webp",
                "label": "pink-flower-233395"
            },
            {
                "src": "Image%20Resources/Flowers/pink-lotus-flower-10683674.jpg.webp",
                "label": "pink-lotus-flower-10683674"
            },
            {
                "src": "Image%20Resources/Flowers/poppy-flower-single-isolated-over-white-background-42630685.jpg.webp",
                "label": "poppy-flower-single-isolated-over-white-background-42630685"
            },
            {
                "src": "Image%20Resources/Flowers/Rose.jpeg",
                "label": "Rose"
            },
            {
                "src": "Image%20Resources/Flowers/single-orchid-flower-floral-background-neutral-39703045.jpg.webp",
                "label": "single-orchid-flower-floral-background-neutral-39703045"
            },
            {
                "src": "Image%20Resources/Flowers/sun%20flower.jpeg",
                "label": "sun flower"
            },
            {
                "src": "Image%20Resources/Flowers/yellow-linden-flower-25182579.jpg.webp",
                "label": "yellow-linden-flower-25182579"
            }
        ]
    },
    {
        "id": "Fruit",
        "name": "Fruit",
        "pairCount": 10,
        "images": [
            {
                "src": "Image%20Resources/Fruit/%20%20Strawberry.jpg",
                "label": "Strawberry"
            },
            {
                "src": "Image%20Resources/Fruit/Apple.jpg",
                "label": "Apple"
            },
            {
                "src": "Image%20Resources/Fruit/Banana.png",
                "label": "Banana"
            },
            {
                "src": "Image%20Resources/Fruit/Blueberry.jpeg",
                "label": "Blueberry"
            },
            {
                "src": "Image%20Resources/Fruit/Cantalope.jpg",
                "label": "Cantalope"
            },
            {
                "src": "Image%20Resources/Fruit/Cherry.jpeg",
                "label": "Cherry"
            },
            {
                "src": "Image%20Resources/Fruit/Fig.jpeg",
                "label": "Fig"
            },
            {
                "src": "Image%20Resources/Fruit/Grapes.jpg",
                "label": "Grapes"
            },
            {
                "src": "Image%20Resources/Fruit/Guava.jpeg",
                "label": "Guava"
            },
            {
                "src": "Image%20Resources/Fruit/Kiwi.jpeg",
                "label": "Kiwi"
            },
            {
                "src": "Image%20Resources/Fruit/Lemon.jpeg",
                "label": "Lemon"
            },
            {
                "src": "Image%20Resources/Fruit/Manago.jpeg",
                "label": "Manago"
            },
            {
                "src": "Image%20Resources/Fruit/Melon.jpg",
                "label": "Melon"
            },
            {
                "src": "Image%20Resources/Fruit/Orange.jpg",
                "label": "Orange"
            },
            {
                "src": "Image%20Resources/Fruit/Papaya.jpeg",
                "label": "Papaya"
            },
            {
                "src": "Image%20Resources/Fruit/Peach.jpg",
                "label": "Peach"
            },
            {
                "src": "Image%20Resources/Fruit/Pineapple.jpg",
                "label": "Pineapple"
            },
            {
                "src": "Image%20Resources/Fruit/Plum.jpeg",
                "label": "Plum"
            },
            {
                "src": "Image%20Resources/Fruit/Rassberry.jpeg",
                "label": "Rassberry"
            },
            {
                "src": "Image%20Resources/Fruit/Watermelon.jpg",
                "label": "Watermelon"
            }
        ]
    },
    {
        "id": "Furniture",
        "name": "Furniture",
        "pairCount": 10,
        "images": [
            {
                "src": "Image%20Resources/Furniture/armchair.svg",
                "label": "armchair"
            },
            {
                "src": "Image%20Resources/Furniture/bed.svg",
                "label": "bed"
            },
            {
                "src": "Image%20Resources/Furniture/bookshelf.svg",
                "label": "bookshelf"
            },
            {
                "src": "Image%20Resources/Furniture/coat-rack.svg",
                "label": "coat-rack"
            },
            {
                "src": "Image%20Resources/Furniture/coffee-table.svg",
                "label": "coffee-table"
            },
            {
                "src": "Image%20Resources/Furniture/desk-lamp.svg",
                "label": "desk-lamp"
            },
            {
                "src": "Image%20Resources/Furniture/dining-chair.svg",
                "label": "dining-chair"
            },
            {
                "src": "Image%20Resources/Furniture/dining-table.svg",
                "label": "dining-table"
            },
            {
                "src": "Image%20Resources/Furniture/nightstand.svg",
                "label": "nightstand"
            },
            {
                "src": "Image%20Resources/Furniture/office-chair.svg",
                "label": "office-chair"
            },
            {
                "src": "Image%20Resources/Furniture/ottoman.svg",
                "label": "ottoman"
            },
            {
                "src": "Image%20Resources/Furniture/rocking-chair.svg",
                "label": "rocking-chair"
            },
            {
                "src": "Image%20Resources/Furniture/shoe-rack.svg",
                "label": "shoe-rack"
            },
            {
                "src": "Image%20Resources/Furniture/side-table.svg",
                "label": "side-table"
            },
            {
                "src": "Image%20Resources/Furniture/sideboard.svg",
                "label": "sideboard"
            },
            {
                "src": "Image%20Resources/Furniture/sofa.svg",
                "label": "sofa"
            },
            {
                "src": "Image%20Resources/Furniture/tv-stand.svg",
                "label": "tv-stand"
            },
            {
                "src": "Image%20Resources/Furniture/wall-mirror.svg",
                "label": "wall-mirror"
            },
            {
                "src": "Image%20Resources/Furniture/wardrobe.svg",
                "label": "wardrobe"
            },
            {
                "src": "Image%20Resources/Furniture/writing-desk.svg",
                "label": "writing-desk"
            }
        ]
    },
    {
        "id": "Travel",
        "name": "Travel",
        "pairCount": 16,
        "images": [
            {
                "src": "Image%20Resources/Travel/Argentina.avif",
                "label": "Argentina"
            },
            {
                "src": "Image%20Resources/Travel/Brazil.avif",
                "label": "Brazil"
            },
            {
                "src": "Image%20Resources/Travel/Canada.avif",
                "label": "Canada"
            },
            {
                "src": "Image%20Resources/Travel/Chile.avif",
                "label": "Chile"
            },
            {
                "src": "Image%20Resources/Travel/China.avif",
                "label": "China"
            },
            {
                "src": "Image%20Resources/Travel/Colombia.avif",
                "label": "Colombia"
            },
            {
                "src": "Image%20Resources/Travel/Costa%20Rica.avif",
                "label": "Costa Rica"
            },
            {
                "src": "Image%20Resources/Travel/Croatia.avif",
                "label": "Croatia"
            },
            {
                "src": "Image%20Resources/Travel/Great%20Wall.jpg",
                "label": "Great Wall"
            },
            {
                "src": "Image%20Resources/Travel/Greece.avif",
                "label": "Greece"
            },
            {
                "src": "Image%20Resources/Travel/Iceland.avif",
                "label": "Iceland"
            },
            {
                "src": "Image%20Resources/Travel/India.avif",
                "label": "India"
            },
            {
                "src": "Image%20Resources/Travel/Indonesia.avif",
                "label": "Indonesia"
            },
            {
                "src": "Image%20Resources/Travel/Italy.avif",
                "label": "Italy"
            },
            {
                "src": "Image%20Resources/Travel/Japan.avif",
                "label": "Japan"
            },
            {
                "src": "Image%20Resources/Travel/Kenya.avif",
                "label": "Kenya"
            },
            {
                "src": "Image%20Resources/Travel/London.avif",
                "label": "London"
            },
            {
                "src": "Image%20Resources/Travel/Madagascar.avif",
                "label": "Madagascar"
            },
            {
                "src": "Image%20Resources/Travel/Mexico.avif",
                "label": "Mexico"
            },
            {
                "src": "Image%20Resources/Travel/Morocco.avif",
                "label": "Morocco"
            },
            {
                "src": "Image%20Resources/Travel/Nepal.avif",
                "label": "Nepal"
            },
            {
                "src": "Image%20Resources/Travel/New%20Zeland.avif",
                "label": "New Zeland"
            },
            {
                "src": "Image%20Resources/Travel/Norway.avif",
                "label": "Norway"
            },
            {
                "src": "Image%20Resources/Travel/Peru.avif",
                "label": "Peru"
            },
            {
                "src": "Image%20Resources/Travel/Philippines.avif",
                "label": "Philippines"
            },
            {
                "src": "Image%20Resources/Travel/Portugal.avif",
                "label": "Portugal"
            },
            {
                "src": "Image%20Resources/Travel/Sweden.avif",
                "label": "Sweden"
            },
            {
                "src": "Image%20Resources/Travel/Switzerland.avif",
                "label": "Switzerland"
            },
            {
                "src": "Image%20Resources/Travel/sydney.jpeg",
                "label": "sydney"
            },
            {
                "src": "Image%20Resources/Travel/Thailand.avif",
                "label": "Thailand"
            },
            {
                "src": "Image%20Resources/Travel/Turkey.avif",
                "label": "Turkey"
            },
            {
                "src": "Image%20Resources/Travel/Vietnam.avif",
                "label": "Vietnam"
            }
        ]
    }
];
