/* AUTO-GENERATED by tools/generate_games.sh -- do not edit by hand.
 * Regenerate with:  bash tools/generate_games.sh
 */
window.GAMES = [
    {
        "id": "Animals",
        "name": "Animals",
        "pairCount": 2,
        "images": [
            {
                "src": "Image%20Resources/Animals/Apple.jpg",
                "label": "Apple"
            },
            {
                "src": "Image%20Resources/Animals/Banana.png",
                "label": "Banana"
            },
            {
                "src": "Image%20Resources/Animals/Hibiscus.jpeg",
                "label": "Hibiscus"
            },
            {
                "src": "Image%20Resources/Animals/lobelia-cardinalis-431547.jpg.webp",
                "label": "lobelia-cardinalis-431547"
            }
        ]
    },
    {
        "id": "Flowers",
        "name": "Flowers",
        "pairCount": 10,
        "images": [
            {
                "src": "Image%20Resources/Flowers/blossoming-orange-pot-marigold-flower-isolated-16334687.jpg.webp",
                "label": "blossoming-orange-pot-marigold-flower-isolated-16334687"
            },
            {
                "src": "Image%20Resources/Flowers/blue-cornflower-flower-head-centaurea-cyanus-16453007.jpg.webp",
                "label": "blue-cornflower-flower-head-centaurea-cyanus-16453007"
            },
            {
                "src": "Image%20Resources/Flowers/dandelion-flower-dphotography.jpg.webp",
                "label": "dandelion-flower-dphotography"
            },
            {
                "src": "Image%20Resources/Flowers/dandelion-seed-flying-away-2262744.jpg.webp",
                "label": "dandelion-seed-flying-away-2262744"
            },
            {
                "src": "Image%20Resources/Flowers/Delphinium.jpeg",
                "label": "Delphinium"
            },
            {
                "src": "Image%20Resources/Flowers/frangipani-plumeria-flower-5201524.jpg.webp",
                "label": "frangipani-plumeria-flower-5201524"
            },
            {
                "src": "Image%20Resources/Flowers/Hibiscus.jpeg",
                "label": "Hibiscus"
            },
            {
                "src": "Image%20Resources/Flowers/lobelia-cardinalis-431547.jpg.webp",
                "label": "lobelia-cardinalis-431547"
            },
            {
                "src": "Image%20Resources/Flowers/lotus-flower-8341397.jpg.webp",
                "label": "lotus-flower-8341397"
            },
            {
                "src": "Image%20Resources/Flowers/lotus-flower-isolated-white-background-39241417.jpg.webp",
                "label": "lotus-flower-isolated-white-background-39241417"
            },
            {
                "src": "Image%20Resources/Flowers/mauve-flower-composition-1-690383.jpg.webp",
                "label": "mauve-flower-composition-1-690383"
            },
            {
                "src": "Image%20Resources/Flowers/orange-color-hibiscus-flower-green-leaves-isolated-white-background-path-orange-color-hibiscus-flower-green-leaves-123652458.jpg.webp",
                "label": "orange-color-hibiscus-flower-green-leaves-isolated-white-background-path-orange-color-hibiscus-flower-green-leaves-123652458"
            },
            {
                "src": "Image%20Resources/Flowers/Pink%20Cherry%20blossom.jpeg",
                "label": "Pink Cherry blossom"
            },
            {
                "src": "Image%20Resources/Flowers/pink-flower-233395.jpg.webp",
                "label": "pink-flower-233395"
            },
            {
                "src": "Image%20Resources/Flowers/pink-lotus-flower-10683674.jpg.webp",
                "label": "pink-lotus-flower-10683674"
            },
            {
                "src": "Image%20Resources/Flowers/poppy-flower-single-isolated-over-white-background-42630685.jpg.webp",
                "label": "poppy-flower-single-isolated-over-white-background-42630685"
            },
            {
                "src": "Image%20Resources/Flowers/Rose.jpeg",
                "label": "Rose"
            },
            {
                "src": "Image%20Resources/Flowers/single-orchid-flower-floral-background-neutral-39703045.jpg.webp",
                "label": "single-orchid-flower-floral-background-neutral-39703045"
            },
            {
                "src": "Image%20Resources/Flowers/sun%20flower.jpeg",
                "label": "sun flower"
            },
            {
                "src": "Image%20Resources/Flowers/yellow-linden-flower-25182579.jpg.webp",
                "label": "yellow-linden-flower-25182579"
            }
        ]
    },
    {
        "id": "Fruit",
        "name": "Fruit",
        "pairCount": 10,
        "images": [
            {
                "src": "Image%20Resources/Fruit/%20%20Strawberry.jpg",
                "label": "Strawberry"
            },
            {
                "src": "Image%20Resources/Fruit/Apple.jpg",
                "label": "Apple"
            },
            {
                "src": "Image%20Resources/Fruit/Banana.png",
                "label": "Banana"
            },
            {
                "src": "Image%20Resources/Fruit/Blueberry.jpeg",
                "label": "Blueberry"
            },
            {
                "src": "Image%20Resources/Fruit/Cantalope.jpg",
                "label": "Cantalope"
            },
            {
                "src": "Image%20Resources/Fruit/Cherry.jpeg",
                "label": "Cherry"
            },
            {
                "src": "Image%20Resources/Fruit/Fig.jpeg",
                "label": "Fig"
            },
            {
                "src": "Image%20Resources/Fruit/Grapes.jpg",
                "label": "Grapes"
            },
            {
                "src": "Image%20Resources/Fruit/Guava.jpeg",
                "label": "Guava"
            },
            {
                "src": "Image%20Resources/Fruit/Kiwi.jpeg",
                "label": "Kiwi"
            },
            {
                "src": "Image%20Resources/Fruit/Lemon.jpeg",
                "label": "Lemon"
            },
            {
                "src": "Image%20Resources/Fruit/Manago.jpeg",
                "label": "Manago"
            },
            {
                "src": "Image%20Resources/Fruit/Melon.jpg",
                "label": "Melon"
            },
            {
                "src": "Image%20Resources/Fruit/Orange.jpg",
                "label": "Orange"
            },
            {
                "src": "Image%20Resources/Fruit/Papaya.jpeg",
                "label": "Papaya"
            },
            {
                "src": "Image%20Resources/Fruit/Peach.jpg",
                "label": "Peach"
            },
            {
                "src": "Image%20Resources/Fruit/Pineapple.jpg",
                "label": "Pineapple"
            },
            {
                "src": "Image%20Resources/Fruit/Plum.jpeg",
                "label": "Plum"
            },
            {
                "src": "Image%20Resources/Fruit/Rassberry.jpeg",
                "label": "Rassberry"
            },
            {
                "src": "Image%20Resources/Fruit/Watermelon.jpg",
                "label": "Watermelon"
            }
        ]
    },
    {
        "id": "Furniture",
        "name": "Furniture",
        "pairCount": 10,
        "images": [
            {
                "src": "Image%20Resources/Furniture/armchair.svg",
                "label": "armchair"
            },
            {
                "src": "Image%20Resources/Furniture/bed.svg",
                "label": "bed"
            },
            {
                "src": "Image%20Resources/Furniture/bookshelf.svg",
                "label": "bookshelf"
            },
            {
                "src": "Image%20Resources/Furniture/coat-rack.svg",
                "label": "coat-rack"
            },
            {
                "src": "Image%20Resources/Furniture/coffee-table.svg",
                "label": "coffee-table"
            },
            {
                "src": "Image%20Resources/Furniture/desk-lamp.svg",
                "label": "desk-lamp"
            },
            {
                "src": "Image%20Resources/Furniture/dining-chair.svg",
                "label": "dining-chair"
            },
            {
                "src": "Image%20Resources/Furniture/dining-table.svg",
                "label": "dining-table"
            },
            {
                "src": "Image%20Resources/Furniture/nightstand.svg",
                "label": "nightstand"
            },
            {
                "src": "Image%20Resources/Furniture/office-chair.svg",
                "label": "office-chair"
            },
            {
                "src": "Image%20Resources/Furniture/ottoman.svg",
                "label": "ottoman"
            },
            {
                "src": "Image%20Resources/Furniture/rocking-chair.svg",
                "label": "rocking-chair"
            },
            {
                "src": "Image%20Resources/Furniture/shoe-rack.svg",
                "label": "shoe-rack"
            },
            {
                "src": "Image%20Resources/Furniture/side-table.svg",
                "label": "side-table"
            },
            {
                "src": "Image%20Resources/Furniture/sideboard.svg",
                "label": "sideboard"
            },
            {
                "src": "Image%20Resources/Furniture/sofa.svg",
                "label": "sofa"
            },
            {
                "src": "Image%20Resources/Furniture/tv-stand.svg",
                "label": "tv-stand"
            },
            {
                "src": "Image%20Resources/Furniture/wall-mirror.svg",
                "label": "wall-mirror"
            },
            {
                "src": "Image%20Resources/Furniture/wardrobe.svg",
                "label": "wardrobe"
            },
            {
                "src": "Image%20Resources/Furniture/writing-desk.svg",
                "label": "writing-desk"
            }
        ]
    },
    {
        "id": "Travel",
        "name": "Travel",
        "pairCount": 0,
        "images": []
    }
];
